[package]
name = "raytracing-rust"
version = "0.1.0"
authors = ["undefined <michael8090@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = "s"
